version: '3.8'

services:
  app:
    build: .
    container_name: finance_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./firebase.json:/app/firebase.json

  postgres:
    image: postgres:16
    container_name: finance_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: finance_redis
    ports:
      - "6379:6379"

volumes:
  pgdata: